# Generated by Django 3.2.19 on 2024-01-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('marks', models.TextField()),
            ],
        ),
    ]
